# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='grant',
            new_name='granted',
        ),
    ]
