# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0004_auto_20190225_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
